# Generated by Django 4.1 on 2025-03-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(blank=True, null=True, verbose_name="diagnosis"),
                ),
                (
                    "events",
                    models.TextField(blank=True, null=True, verbose_name="events"),
                ),
                (
                    "water",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="water"
                    ),
                ),
                (
                    "feeding",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="feeding"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
            ],
            options={
                "db_table": "Diagnosis",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "events",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="events"
                    ),
                ),
                ("url", models.URLField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
            ],
            options={
                "db_table": "Events",
                "ordering": ["id"],
            },
        ),
    ]
