# Generated by Django 4.1 on 2025-04-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diagnosis",
            name="diagnosis",
        ),
        migrations.RemoveField(
            model_name="diagnosis",
            name="events",
        ),
        migrations.RemoveField(
            model_name="diagnosis",
            name="feeding",
        ),
        migrations.RemoveField(
            model_name="diagnosis",
            name="water",
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="analyzed_image",
            field=models.ImageField(blank=True, null=True, upload_to="diagnosticos/"),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="model_answer",
            field=models.TextField(blank=True, null=True, verbose_name="model_answer"),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="model_result",
            field=models.TextField(blank=True, null=True, verbose_name="model_result"),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="ubicacion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="aprobbed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="events",
            name="observation",
            field=models.TextField(blank=True, null=True, verbose_name="observation"),
        ),
        migrations.AlterField(
            model_name="events",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="events"),
        ),
    ]
