# Generated by Django 4.1 on 2025-04-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "diagnosis",
            "0003_remove_diagnosis_diagnosis_remove_diagnosis_events_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="aprobbed",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
