# Generated by Django 4.1 on 2025-04-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0004_alter_events_aprobbed"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated_at"),
        ),
    ]
