# Generated by Django 4.1 on 2025-04-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0007_alter_diagnosis_model_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="aprobbed",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
