# Generated by Django 4.1 on 2025-06-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0008_alter_events_aprobbed"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
