name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy files to EC2
        run: |
          rsync -avz --exclude '__pycache__' --exclude '*.pyc' -e "ssh -o StrictHostKeyChecking=no -i key.pem" ./ ec2-user@${{ secrets.EC2_HOST }}:~/app

      - name: SSH and run deploy script
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/app
          docker-compose down
          docker-compose build
          docker-compose up -d
          EOF
